using LeagueToolkit.Core.Environment;

namespace ReyEngine.Formats.MapGeo;

/// <summary>Removes selected environment-mesh records while leaving shared vertex/index buffers intact.
/// The now-unused buffers are harmless and retaining them avoids renumbering every surviving mesh. Bucket
/// grids must be regenerated by the caller because their baked scene geometry includes removed triangles.</summary>
public static class MapGeoMeshRemover
{
    public static byte[]? Remove(byte[] mapgeo, IReadOnlyCollection<int> meshIndices, out string? error)
    {
        error = null;
        if (meshIndices.Count == 0) return mapgeo;
        try
        {
            var sections = MapGeoMeshAppender.WalkSections(mapgeo);
            var remove = meshIndices.ToHashSet();
            if (remove.Any(i => i < 0 || i >= sections.MeshCount))
            {
                error = "A selected mesh index is outside the mapgeo mesh table.";
                return null;
            }

            using var output = new MemoryStream(mapgeo.Length);
            using var writer = new BinaryWriter(output);
            writer.Write(mapgeo, 0, sections.MeshCountOffset);
            writer.Write((uint)(sections.MeshCount - remove.Count));
            for (int i = 0; i < sections.MeshCount; i++)
            {
                if (remove.Contains(i)) continue;
                int start = sections.MeshRecordStarts[i];
                writer.Write(mapgeo, start, sections.MeshRecordEnds[i] - start);
            }
            writer.Write(mapgeo, sections.TailOffset, mapgeo.Length - sections.TailOffset);
            var result = output.ToArray();

            using var verify = new MemoryStream(result, writable: false);
            using var env = new EnvironmentAsset(verify);
            if (env.Meshes.Count != sections.MeshCount - remove.Count)
            {
                error = $"Removed mapgeo re-opened with {env.Meshes.Count} meshes; expected {sections.MeshCount - remove.Count}.";
                return null;
            }
            return result;
        }
        catch (Exception ex)
        {
            error = ex.Message;
            return null;
        }
    }
}
