using LeagueToolkit.Core.Environment;

namespace ReyEngine.Formats.MapGeo;

/// <summary>Removes selected environment-mesh records, then drops the vertex/index buffers and declarations
/// that no surviving mesh references. Bucket grids must be regenerated by the caller because their baked scene
/// geometry includes removed triangles.
///
/// <para>M768: until M768 the buffers were left in the file on purpose, as "harmless". The game may not mind,
/// but LTK Manager's loader refuses the whole map ("Vertex buffer 2213 is not referenced by any mesh" - the
/// user's Classic Rift - Halloween port, after two Add Mesh meshes were deleted), and Riot never ships one.
/// The surviving meshes are renumbered through <see cref="MapGeoBinary.Compact"/>, which is byte-identical on
/// every Riot mapgeo.</para></summary>
public static class MapGeoMeshRemover
{
    public static byte[]? Remove(byte[] mapgeo, IReadOnlyCollection<int> meshIndices, out string? error,
        IReadOnlySet<string>? extendedChannelMaterials = null)
    {
        error = null;
        if (meshIndices.Count == 0) return mapgeo;
        try
        {
            var sections = MapGeoMeshAppender.WalkSections(mapgeo);
            var remove = meshIndices.ToHashSet();
            if (remove.Any(i => i < 0 || i >= sections.MeshCount))
            {
                error = "A selected mesh index is outside the mapgeo mesh table.";
                return null;
            }

            using var output = new MemoryStream(mapgeo.Length);
            using var writer = new BinaryWriter(output);
            writer.Write(mapgeo, 0, sections.MeshCountOffset);
            writer.Write((uint)(sections.MeshCount - remove.Count));
            for (int i = 0; i < sections.MeshCount; i++)
            {
                if (remove.Contains(i)) continue;
                int start = sections.MeshRecordStarts[i];
                writer.Write(mapgeo, start, sections.MeshRecordEnds[i] - start);
            }
            writer.Write(mapgeo, sections.TailOffset, mapgeo.Length - sections.TailOffset);
            var spliced = output.ToArray();

            // M768: and the buffers only the removed meshes used. A file that will not re-read exactly is
            // refused rather than written with orphans LTK Manager rejects.
            if (!MapGeoBinary.TryReadEditable(spliced, out var editable, extendedChannelMaterials))
            {
                error = "The mapgeo did not re-read exactly after removing the meshes, so its unused buffers could not be dropped safely.";
                return null;
            }
            editable.Compact();
            var result = editable.Write();

            using var verify = new MemoryStream(result, writable: false);
            using var env = new EnvironmentAsset(verify);
            if (env.Meshes.Count != sections.MeshCount - remove.Count)
            {
                error = $"Removed mapgeo re-opened with {env.Meshes.Count} meshes; expected {sections.MeshCount - remove.Count}.";
                return null;
            }
            return result;
        }
        catch (Exception ex)
        {
            error = ex.Message;
            return null;
        }
    }
}
